/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u178)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u195)(NimStringV2* result_p0, NI x_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u195)(NimStringV2* result_p0, NI x_p1) {
	addInt__stdZprivateZdigitsutils_u178(result_p0, ((NI64) (x_p1)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	addInt__stdZprivateZdigitsutils_u195((&result), x_p0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u11)(NI64 x_p0) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	addInt__stdZprivateZdigitsutils_u178((&result), x_p0);
	return result;
}
