/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Sha2Context__goYsAtgAvGNLPnJjhh0cLw tyObject_Sha2Context__goYsAtgAvGNLPnJjhh0cLw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Sha2Context__7QmwGx9atx9cCgLpi8MCJDqA tyObject_Sha2Context__7QmwGx9atx9cCgLpi8MCJDqA;
typedef struct tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw;
typedef struct tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ;
typedef struct tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg;
typedef struct tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw;
typedef NU32 tyArray__cVaZ0eskK2VoyoXuwrJrYw[64];
typedef NU64 tyArray__hPrcw5mUju9bhG2eUWCnieQ[80];
typedef NU8 tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg;
typedef NU8 tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg;
typedef NU16 tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA;
typedef NU8 tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU32 tyArray__MpWsq9bBH14GsDQQ59cgyxAQ[8];
typedef NU8 tyArray__Zu7UusKTJ9auYSy2NZNrWFg[128];
typedef N_NIMCALL_PTR(void, tyProc__5N2CuiVyGQ8ceSoFuEBWLg) (NU32* state_p0, NU8* data_p1, NI data_p1Len_0, NI blocks_p2);
struct tyObject_Sha2Context__goYsAtgAvGNLPnJjhh0cLw {
NIM_ALIGN(32) 	tyArray__MpWsq9bBH14GsDQQ59cgyxAQ state;
NIM_ALIGN(32) 	tyArray__Zu7UusKTJ9auYSy2NZNrWFg buffer;
	tyProc__5N2CuiVyGQ8ceSoFuEBWLg compressFunc;
	NU64 length;
	NI reminder;
};
struct tyObject_Sha2Context__7QmwGx9atx9cCgLpi8MCJDqA {
NIM_ALIGN(32) 	tyArray__MpWsq9bBH14GsDQQ59cgyxAQ state;
NIM_ALIGN(32) 	tyArray__Zu7UusKTJ9auYSy2NZNrWFg buffer;
	tyProc__5N2CuiVyGQ8ceSoFuEBWLg compressFunc;
	NU64 length;
	NI reminder;
};
typedef NU64 tyArray__9cHI9ce3NOVpqam1bGmXg5vw[8];
typedef NU8 tyArray__Cxe6prgo05ftSyAqRHalCw[256];
typedef N_NIMCALL_PTR(void, tyProc__9cdaqClWTHGDoeyBthOw44w) (NU64* state_p0, NU8* data_p1, NI data_p1Len_0, NI blocks_p2);
struct tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw {
NIM_ALIGN(32) 	tyArray__9cHI9ce3NOVpqam1bGmXg5vw state;
NIM_ALIGN(32) 	tyArray__Cxe6prgo05ftSyAqRHalCw buffer;
	tyProc__9cdaqClWTHGDoeyBthOw44w compressFunc;
	NU64 length;
	NI reminder;
};
struct tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ {
NIM_ALIGN(32) 	tyArray__9cHI9ce3NOVpqam1bGmXg5vw state;
NIM_ALIGN(32) 	tyArray__Cxe6prgo05ftSyAqRHalCw buffer;
	tyProc__9cdaqClWTHGDoeyBthOw44w compressFunc;
	NU64 length;
	NI reminder;
};
struct tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg {
NIM_ALIGN(32) 	tyArray__9cHI9ce3NOVpqam1bGmXg5vw state;
NIM_ALIGN(32) 	tyArray__Cxe6prgo05ftSyAqRHalCw buffer;
	tyProc__9cdaqClWTHGDoeyBthOw44w compressFunc;
	NU64 length;
	NI reminder;
};
struct tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw {
NIM_ALIGN(32) 	tyArray__9cHI9ce3NOVpqam1bGmXg5vw state;
NIM_ALIGN(32) 	tyArray__Cxe6prgo05ftSyAqRHalCw buffer;
	tyProc__9cdaqClWTHGDoeyBthOw44w compressFunc;
	NU64 length;
	NI reminder;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u40)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u649)(tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw* ctx_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u819)(tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u974)(tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u1124)(tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[56+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_2 = { 56 | NIM_STRLIT_FLAG, "AVX implementation is not available on [x86_64] platform" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_3 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const struct {
  NI cap; NIM_CHAR data[57+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_4 = { 57 | NIM_STRLIT_FLAG, "AVX2 implementation is not available on [x86_64] platform" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_5 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const struct {
  NI cap; NIM_CHAR data[52+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_6 = { 52 | NIM_STRLIT_FLAG, "SHA2 extension is not available on [x86_64] platform" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_7 = {52, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_6};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_8 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_9 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_10 = {52, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_6};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_11 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_12 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_13 = { 8 | NIM_STRLIT_FLAG, "SHA2-384" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_14 = {8, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_13};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_17 = { 60 | NIM_STRLIT_FLAG, " is not supported by SHA extensions yet on [x86_64] platform" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_18 = {60, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_17};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_19 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_20 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_21 = { 8 | NIM_STRLIT_FLAG, "SHA2-512" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_22 = {8, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_21};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_23 = {60, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_17};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_24 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_25 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_26 = { 12 | NIM_STRLIT_FLAG, "SHA2-512/224" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_27 = {12, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_26};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_28 = {60, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_17};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_29 = {56, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_2};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_30 = {57, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9ci8WQSavmh9cLQptYkLGKBg_31 = { 12 | NIM_STRLIT_FLAG, "SHA2-512/256" };
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_32 = {12, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_31};
static const NimStringV2 TM__9ci8WQSavmh9cLQptYkLGKBg_33 = {60, (NimStrPayload*)&TM__9ci8WQSavmh9cLQptYkLGKBg_17};
N_LIB_PRIVATE NIM_CONST tyArray__cVaZ0eskK2VoyoXuwrJrYw K0__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha5095common_u4 = {((NU32)1116352408),
((NU32)1899447441),
((NU32)IL64(3049323471)),
((NU32)IL64(3921009573)),
((NU32)961987163),
((NU32)1508970993),
((NU32)IL64(2453635748)),
((NU32)IL64(2870763221)),
((NU32)IL64(3624381080)),
((NU32)310598401),
((NU32)607225278),
((NU32)1426881987),
((NU32)1925078388),
((NU32)IL64(2162078206)),
((NU32)IL64(2614888103)),
((NU32)IL64(3248222580)),
((NU32)IL64(3835390401)),
((NU32)IL64(4022224774)),
((NU32)264347078),
((NU32)604807628),
((NU32)770255983),
((NU32)1249150122),
((NU32)1555081692),
((NU32)1996064986),
((NU32)IL64(2554220882)),
((NU32)IL64(2821834349)),
((NU32)IL64(2952996808)),
((NU32)IL64(3210313671)),
((NU32)IL64(3336571891)),
((NU32)IL64(3584528711)),
((NU32)113926993),
((NU32)338241895),
((NU32)666307205),
((NU32)773529912),
((NU32)1294757372),
((NU32)1396182291),
((NU32)1695183700),
((NU32)1986661051),
((NU32)IL64(2177026350)),
((NU32)IL64(2456956037)),
((NU32)IL64(2730485921)),
((NU32)IL64(2820302411)),
((NU32)IL64(3259730800)),
((NU32)IL64(3345764771)),
((NU32)IL64(3516065817)),
((NU32)IL64(3600352804)),
((NU32)IL64(4094571909)),
((NU32)275423344),
((NU32)430227734),
((NU32)506948616),
((NU32)659060556),
((NU32)883997877),
((NU32)958139571),
((NU32)1322822218),
((NU32)1537002063),
((NU32)1747873779),
((NU32)1955562222),
((NU32)2024104815),
((NU32)IL64(2227730452)),
((NU32)IL64(2361852424)),
((NU32)IL64(2428436474)),
((NU32)IL64(2756734187)),
((NU32)IL64(3204031479)),
((NU32)IL64(3329325298))}
;
N_LIB_PRIVATE NIM_CONST tyArray__hPrcw5mUju9bhG2eUWCnieQ K1__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha5095common_u5 = {4794697086780616226ULL,
8158064640168781261ULL,
13096744586834688815ULL,
16840607885511220156ULL,
4131703408338449720ULL,
6480981068601479193ULL,
10538285296894168987ULL,
12329834152419229976ULL,
15566598209576043074ULL,
1334009975649890238ULL,
2608012711638119052ULL,
6128411473006802146ULL,
8268148722764581231ULL,
9286055187155687089ULL,
11230858885718282805ULL,
13951009754708518548ULL,
16472876342353939154ULL,
17275323862435702243ULL,
1135362057144423861ULL,
2597628984639134821ULL,
3308224258029322869ULL,
5365058923640841347ULL,
6679025012923562964ULL,
8573033837759648693ULL,
10970295158949994411ULL,
12119686244451234320ULL,
12683024718118986047ULL,
13788192230050041572ULL,
14330467153632333762ULL,
15395433587784984357ULL,
489312712824947311ULL,
1452737877330783856ULL,
2861767655752347644ULL,
3322285676063803686ULL,
5560940570517711597ULL,
5996557281743188959ULL,
7280758554555802590ULL,
8532644243296465576ULL,
9350256976987008742ULL,
10552545826968843579ULL,
11727347734174303076ULL,
12113106623233404929ULL,
14000437183269869457ULL,
14369950271660146224ULL,
15101387698204529176ULL,
15463397548674623760ULL,
17586052441742319658ULL,
1182934255886127544ULL,
1847814050463011016ULL,
2177327727835720531ULL,
2830643537854262169ULL,
3796741975233480872ULL,
4115178125766777443ULL,
5681478168544905931ULL,
6601373596472566643ULL,
7507060721942968483ULL,
8399075790359081724ULL,
8693463985226723168ULL,
9568029438360202098ULL,
10144078919501101548ULL,
10430055236837252648ULL,
11840083180663258601ULL,
13761210420658862357ULL,
14299343276471374635ULL,
14566680578165727644ULL,
15097957966210449927ULL,
16922976911328602910ULL,
17689382322260857208ULL,
500013540394364858ULL,
748580250866718886ULL,
1242879168328830382ULL,
1977374033974150939ULL,
2944078676154940804ULL,
3659926193048069267ULL,
4368137639120453308ULL,
4836135668995329356ULL,
5532061633213252278ULL,
6448918945643986474ULL,
6902733635092675308ULL,
7801388544844847127ULL}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u284)(tyObject_Sha2Context__goYsAtgAvGNLPnJjhh0cLw* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)6)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)3);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA9_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA13_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA13_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA21_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__6;
		}
		goto LA19_;
LA21_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__7;
		colontmpD__7 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA27_;
			colontmpD__7 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__7;
		}
		goto LA25_;
LA27_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA25_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__8;
		colontmpD__8 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)6)))&15U)))!=0)) goto LA33_;
			colontmpD__8 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)3);
			colontmpD__5 = colontmpD__8;
		}
		goto LA31_;
LA33_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_7);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA31_: ;
		result = colontmpD__5;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u471)(tyObject_Sha2Context__7QmwGx9atx9cCgLpi8MCJDqA* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)6)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)3);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA9_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA13_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA13_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA21_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__6;
		}
		goto LA19_;
LA21_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_8);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__7;
		colontmpD__7 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA27_;
			colontmpD__7 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__7;
		}
		goto LA25_;
LA27_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_9);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA25_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__8;
		colontmpD__8 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)6)))&15U)))!=0)) goto LA33_;
			colontmpD__8 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)3);
			colontmpD__5 = colontmpD__8;
		}
		goto LA31_;
LA33_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_10);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA31_: ;
		result = colontmpD__5;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u649)(tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw* ctx_p0) {
	NimStringV2 result;
	result = TM__9ci8WQSavmh9cLQptYkLGKBg_14;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__9ci8WQSavmh9cLQptYkLGKBg_15;
		NI TM__9ci8WQSavmh9cLQptYkLGKBg_16;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if (nimAddInt(src_p1.len, ((NI)1), &TM__9ci8WQSavmh9cLQptYkLGKBg_15)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__9ci8WQSavmh9cLQptYkLGKBg_15)) < ((NI)0) || ((NI)(TM__9ci8WQSavmh9cLQptYkLGKBg_15)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__9ci8WQSavmh9cLQptYkLGKBg_15), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1745(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI) ((NI)(TM__9ci8WQSavmh9cLQptYkLGKBg_15))));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__9ci8WQSavmh9cLQptYkLGKBg_16)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__9ci8WQSavmh9cLQptYkLGKBg_16);
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u625)(tyObject_Sha2Context__cjOVHg4EcKEDhibFbXt3uw* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA9_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
		colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA17_;
			colontmpD__5 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__5;
		}
		goto LA15_;
LA17_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_11);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA23_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__6;
		}
		goto LA21_;
LA23_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_12);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA21_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		NimStringV2 colontmpD__7;
		NimStringV2 colontmpD__8;
		NimStringV2 T27_;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
		T27_.len = 0; T27_.p = NIM_NIL;
		colontmpD__7 = name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u649(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T27_ = rawNewString(colontmpD__7.len + 60);
appendString((&T27_), colontmpD__7);
appendString((&T27_), TM__9ci8WQSavmh9cLQptYkLGKBg_18);
		colontmpD__8 = T27_;
		raiseAssert__stdZassertions_u40(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u819)(tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ* ctx_p0) {
	NimStringV2 result;
	result = TM__9ci8WQSavmh9cLQptYkLGKBg_22;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u795)(tyObject_Sha2Context__Ijn4SkZq7O3yjC1S2QhNkQ* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA9_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
		colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA17_;
			colontmpD__5 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__5;
		}
		goto LA15_;
LA17_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_19);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA23_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__6;
		}
		goto LA21_;
LA23_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_20);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA21_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		NimStringV2 colontmpD__7;
		NimStringV2 colontmpD__8;
		NimStringV2 T27_;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
		T27_.len = 0; T27_.p = NIM_NIL;
		colontmpD__7 = name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u819(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T27_ = rawNewString(colontmpD__7.len + 60);
appendString((&T27_), colontmpD__7);
appendString((&T27_), TM__9ci8WQSavmh9cLQptYkLGKBg_23);
		colontmpD__8 = T27_;
		raiseAssert__stdZassertions_u40(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u974)(tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg* ctx_p0) {
	NimStringV2 result;
	result = TM__9ci8WQSavmh9cLQptYkLGKBg_27;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u950)(tyObject_Sha2Context__oXlPICN9bx30BCAmCUXTmQg* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA9_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
		colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA17_;
			colontmpD__5 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__5;
		}
		goto LA15_;
LA17_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_24);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA23_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__6;
		}
		goto LA21_;
LA23_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_25);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA21_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		NimStringV2 colontmpD__7;
		NimStringV2 colontmpD__8;
		NimStringV2 T27_;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
		T27_.len = 0; T27_.p = NIM_NIL;
		colontmpD__7 = name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u974(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T27_ = rawNewString(colontmpD__7.len + 60);
appendString((&T27_), colontmpD__7);
appendString((&T27_), TM__9ci8WQSavmh9cLQptYkLGKBg_28);
		colontmpD__8 = T27_;
		raiseAssert__stdZassertions_u40(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u1124)(tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw* ctx_p0) {
	NimStringV2 result;
	result = TM__9ci8WQSavmh9cLQptYkLGKBg_32;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg, getImplementation__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u1100)(tyObject_Sha2Context__MoFCrBshLQLnYioxTOB49bw* ctx_p0, tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg implementation_p1, tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA features_p2) {
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg result;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD_;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__2;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__3;
	tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD_ = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__2 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__3 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	colontmpD__4 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
	switch (implementation_p1) {
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)4):
	{
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA5_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			goto BeforeRet_;
		}
LA5_: ;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA9_;
			result = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			goto BeforeRet_;
		}
LA9_: ;
		colontmpD_ = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD_;
		{
			LA2_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)0):
	{
		colontmpD__2 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)1):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__5;
		colontmpD__5 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2)))&15U)))!=0)) goto LA17_;
			colontmpD__5 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)1);
			colontmpD__3 = colontmpD__5;
		}
		goto LA15_;
LA17_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_29);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
		result = colontmpD__3;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)2):
	{
		tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg colontmpD__6;
		colontmpD__6 = (tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)0;
		{
			if (!((features_p2 &((NU16)1<<((NU)((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3)))&15U)))!=0)) goto LA23_;
			colontmpD__6 = ((tyEnum_Sha2Module__67PA5sAYkkp3GoAfgUz6Jg)2);
			colontmpD__4 = colontmpD__6;
		}
		goto LA21_;
LA23_: ;
		{
			raiseAssert__stdZassertions_u40(TM__9ci8WQSavmh9cLQptYkLGKBg_30);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA21_: ;
		result = colontmpD__4;
	}
	break;
	case ((tyEnum_Sha2Implementation__io9bkSxGSaP9bHLuzDARS0dg)3):
	{
		NimStringV2 colontmpD__7;
		NimStringV2 colontmpD__8;
		NimStringV2 T27_;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
		T27_.len = 0; T27_.p = NIM_NIL;
		colontmpD__7 = name__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha50_u1124(ctx_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T27_ = rawNewString(colontmpD__7.len + 60);
appendString((&T27_), colontmpD__7);
appendString((&T27_), TM__9ci8WQSavmh9cLQptYkLGKBg_33);
		colontmpD__8 = T27_;
		raiseAssert__stdZassertions_u40(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
