/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <x86intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU64 tyArray__NzKR9bw29cLPrd712Xt6Liiw[2];
typedef __m128i tyArray__hj9cIoekIj9cgg8gElCi6bBw[4];
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, sha256Compress__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZsha50Zsha5095sha_u67)(NU32* state_p0, NU8* data_p1, NI data_p1Len_0, NI blocks_p2) {
	NIM_ALIGN(32) __m128i shufMask;
	tyArray__hj9cIoekIj9cgg8gElCi6bBw msgtmp;
	NIM_ALIGN(32) __m128i msg;
	NIM_ALIGN(32) __m128i tmp;
	__m128i T1_;
	NIM_ALIGN(32) __m128i state1;
	__m128i T2_;
	NIM_ALIGN(32) __m128i state0;
	NI blocksCount;
	NI offset;
{	shufMask = _mm_set_epi64x(868365760874482187ULL, 289644378169868803ULL);
	T1_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&state_p0[(((NI)0))- 0]))))));
	tmp = _mm_shuffle_epi32(T1_, ((NU32)177));
	T2_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&state_p0[(((NI)4))- 0]))))));
	state1 = _mm_shuffle_epi32(T2_, ((NU32)27));
	state0 = _mm_alignr_epi8(tmp, state1, ((NU32)8));
	blocksCount = blocks_p2;
	offset = ((NI)0);
	state1 = _mm_blend_epi16(state1, tmp, ((NU32)240));
	{
		while (1) {
			__m128i state0_save;
			__m128i state1_save;
			__m128i T5_;
			__m128i T6_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_2;
			__m128i T7_;
			__m128i T8_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_3;
			__m128i T9_;
			__m128i T10_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_4;
			__m128i T11_;
			__m128i T12_;
			__m128i T13_;
			__m128i T14_;
			__m128i T15_;
			__m128i T16_;
			__m128i T17_;
			__m128i T18_;
			__m128i T19_;
			__m128i T20_;
			__m128i T21_;
			__m128i T22_;
			__m128i T23_;
			__m128i T24_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_5;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_6;
			if (!(((NI)0) < blocksCount)) goto LA4;
			state0_save = state0;
			state1_save = state1;
			if (offset < 0 || offset >= data_p1Len_0){ raiseIndexError2(offset,data_p1Len_0-1); goto BeforeRet_;
			}
			T5_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&data_p1[offset]))))));
			msgtmp[(((NI)0))- 0] = _mm_shuffle_epi8(T5_, shufMask);
			T6_ = _mm_setr_epi32(((NU32)1116352408), ((NU32)1899447441), ((NU32)IL64(3049323471)), ((NU32)IL64(3921009573)));
			msg = _mm_add_epi32(msgtmp[(((NI)0))- 0], T6_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			if (nimAddInt(offset, ((NI)16), &TM__QMTBJ3B2LA4Z4wAiKYiWww_2)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2),data_p1Len_0-1); goto BeforeRet_;
			}
			T7_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2)]))))));
			msgtmp[(((NI)1))- 0] = _mm_shuffle_epi8(T7_, shufMask);
			T8_ = _mm_setr_epi32(((NU32)961987163), ((NU32)1508970993), ((NU32)IL64(2453635748)), ((NU32)IL64(2870763221)));
			msg = _mm_add_epi32(msgtmp[(((NI)1))- 0], T8_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)1))- 0]);
			if (nimAddInt(offset, ((NI)32), &TM__QMTBJ3B2LA4Z4wAiKYiWww_3)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3),data_p1Len_0-1); goto BeforeRet_;
			}
			T9_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3)]))))));
			msgtmp[(((NI)2))- 0] = _mm_shuffle_epi8(T9_, shufMask);
			T10_ = _mm_setr_epi32(((NU32)IL64(3624381080)), ((NU32)310598401), ((NU32)607225278), ((NU32)1426881987));
			msg = _mm_add_epi32(msgtmp[(((NI)2))- 0], T10_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)2))- 0]);
			if (nimAddInt(offset, ((NI)48), &TM__QMTBJ3B2LA4Z4wAiKYiWww_4)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4),data_p1Len_0-1); goto BeforeRet_;
			}
			T11_ = _mm_loadu_si128(((__m128i*) (((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4)]))))));
			msgtmp[(((NI)3))- 0] = _mm_shuffle_epi8(T11_, shufMask);
			T12_ = _mm_setr_epi32(((NU32)1925078388), ((NU32)IL64(2162078206)), ((NU32)IL64(2614888103)), ((NU32)IL64(3248222580)));
			msg = _mm_add_epi32(msgtmp[(((NI)3))- 0], T12_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0], ((NU32)4));
			msgtmp[(((NI)0))- 0] = _mm_add_epi32(msgtmp[(((NI)0))- 0], tmp);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)3))- 0]);
			T13_ = _mm_setr_epi32(((NU32)IL64(3835390401)), ((NU32)IL64(4022224774)), ((NU32)264347078), ((NU32)604807628));
			msg = _mm_add_epi32(msgtmp[(((NI)0))- 0], T13_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0], ((NU32)4));
			msgtmp[(((NI)1))- 0] = _mm_add_epi32(msgtmp[(((NI)1))- 0], tmp);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)0))- 0]);
			T14_ = _mm_setr_epi32(((NU32)770255983), ((NU32)1249150122), ((NU32)1555081692), ((NU32)1996064986));
			msg = _mm_add_epi32(msgtmp[(((NI)1))- 0], T14_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0], ((NU32)4));
			msgtmp[(((NI)2))- 0] = _mm_add_epi32(msgtmp[(((NI)2))- 0], tmp);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)1))- 0]);
			T15_ = _mm_setr_epi32(((NU32)IL64(2554220882)), ((NU32)IL64(2821834349)), ((NU32)IL64(2952996808)), ((NU32)IL64(3210313671)));
			msg = _mm_add_epi32(msgtmp[(((NI)2))- 0], T15_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0], ((NU32)4));
			msgtmp[(((NI)3))- 0] = _mm_add_epi32(msgtmp[(((NI)3))- 0], tmp);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)2))- 0]);
			T16_ = _mm_setr_epi32(((NU32)IL64(3336571891)), ((NU32)IL64(3584528711)), ((NU32)113926993), ((NU32)338241895));
			msg = _mm_add_epi32(msgtmp[(((NI)3))- 0], T16_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0], ((NU32)4));
			msgtmp[(((NI)0))- 0] = _mm_add_epi32(msgtmp[(((NI)0))- 0], tmp);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)3))- 0]);
			T17_ = _mm_setr_epi32(((NU32)666307205), ((NU32)773529912), ((NU32)1294757372), ((NU32)1396182291));
			msg = _mm_add_epi32(msgtmp[(((NI)0))- 0], T17_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0], ((NU32)4));
			msgtmp[(((NI)1))- 0] = _mm_add_epi32(msgtmp[(((NI)1))- 0], tmp);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)0))- 0]);
			T18_ = _mm_setr_epi32(((NU32)1695183700), ((NU32)1986661051), ((NU32)IL64(2177026350)), ((NU32)IL64(2456956037)));
			msg = _mm_add_epi32(msgtmp[(((NI)1))- 0], T18_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0], ((NU32)4));
			msgtmp[(((NI)2))- 0] = _mm_add_epi32(msgtmp[(((NI)2))- 0], tmp);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)1))- 0]);
			T19_ = _mm_setr_epi32(((NU32)IL64(2730485921)), ((NU32)IL64(2820302411)), ((NU32)IL64(3259730800)), ((NU32)IL64(3345764771)));
			msg = _mm_add_epi32(msgtmp[(((NI)2))- 0], T19_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0], ((NU32)4));
			msgtmp[(((NI)3))- 0] = _mm_add_epi32(msgtmp[(((NI)3))- 0], tmp);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)2))- 0]);
			T20_ = _mm_setr_epi32(((NU32)IL64(3516065817)), ((NU32)IL64(3600352804)), ((NU32)IL64(4094571909)), ((NU32)275423344));
			msg = _mm_add_epi32(msgtmp[(((NI)3))- 0], T20_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0], ((NU32)4));
			msgtmp[(((NI)0))- 0] = _mm_add_epi32(msgtmp[(((NI)0))- 0], tmp);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)3))- 0]);
			T21_ = _mm_setr_epi32(((NU32)430227734), ((NU32)506948616), ((NU32)659060556), ((NU32)883997877));
			msg = _mm_add_epi32(msgtmp[(((NI)0))- 0], T21_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)0))- 0], msgtmp[(((NI)3))- 0], ((NU32)4));
			msgtmp[(((NI)1))- 0] = _mm_add_epi32(msgtmp[(((NI)1))- 0], tmp);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)0))- 0]);
			T22_ = _mm_setr_epi32(((NU32)958139571), ((NU32)1322822218), ((NU32)1537002063), ((NU32)1747873779));
			msg = _mm_add_epi32(msgtmp[(((NI)1))- 0], T22_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)1))- 0], msgtmp[(((NI)0))- 0], ((NU32)4));
			msgtmp[(((NI)2))- 0] = _mm_add_epi32(msgtmp[(((NI)2))- 0], tmp);
			msgtmp[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)0))- 0], msgtmp[(((NI)1))- 0]);
			T23_ = _mm_setr_epi32(((NU32)1955562222), ((NU32)2024104815), ((NU32)IL64(2227730452)), ((NU32)IL64(2361852424)));
			msg = _mm_add_epi32(msgtmp[(((NI)2))- 0], T23_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			tmp = _mm_alignr_epi8(msgtmp[(((NI)2))- 0], msgtmp[(((NI)1))- 0], ((NU32)4));
			msgtmp[(((NI)3))- 0] = _mm_add_epi32(msgtmp[(((NI)3))- 0], tmp);
			msgtmp[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp[(((NI)3))- 0], msgtmp[(((NI)2))- 0]);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			msgtmp[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp[(((NI)1))- 0], msgtmp[(((NI)2))- 0]);
			T24_ = _mm_setr_epi32(((NU32)IL64(2428436474)), ((NU32)IL64(2756734187)), ((NU32)IL64(3204031479)), ((NU32)IL64(3329325298)));
			msg = _mm_add_epi32(msgtmp[(((NI)3))- 0], T24_);
			state1 = _mm_sha256rnds2_epu32(state1, state0, msg);
			msg = _mm_shuffle_epi32(msg, ((NU32)14));
			state0 = _mm_sha256rnds2_epu32(state0, state1, msg);
			state0 = _mm_add_epi32(state0, state0_save);
			state1 = _mm_add_epi32(state1, state1_save);
			if (nimAddInt(offset, ((NI)64), &TM__QMTBJ3B2LA4Z4wAiKYiWww_5)) { raiseOverflow(); goto BeforeRet_;
			};
			offset = (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_5);
			if (nimSubInt(blocksCount, ((NI)1), &TM__QMTBJ3B2LA4Z4wAiKYiWww_6)) { raiseOverflow(); goto BeforeRet_;
			};
			blocksCount = (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_6);
		} LA4: ;
	}
	tmp = _mm_shuffle_epi32(state0, ((NU32)27));
	state1 = _mm_shuffle_epi32(state1, ((NU32)177));
	state0 = _mm_blend_epi16(tmp, state1, ((NU32)240));
	state1 = _mm_alignr_epi8(state1, tmp, ((NU32)8));
	_mm_store_si128(((__m128i*) (((__m128i*) ((&state_p0[(((NI)0))- 0]))))), state0);
	_mm_store_si128(((__m128i*) (((__m128i*) ((&state_p0[(((NI)4))- 0]))))), state1);
	}BeforeRet_: ;
}
