/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg;
typedef struct tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg;
typedef struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content;
typedef struct tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg {
  NI len; tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg trace;
	Exception* up;
};
struct tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw {
  Exception Sup;
};
struct tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg {
  tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw Sup;
};
struct tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content { NI cap; tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg data[SEQ_DECL_SIZE]; };
static N_INLINE(void, sysFatal__stdZassertions_u42)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___stdZassertions_u27)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___stdZassertions_u33)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u40)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern TNimTypeV2 NTIv2__ZtpkNCsFg9clzpeO8KwUyVg_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
static N_INLINE(void, sysFatal__stdZassertions_u42)(NimStringV2 message_p1) {
	tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = NIM_NIL;
	T2_ = (tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg*) nimNewObj(sizeof(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg), NIM_ALIGNOF(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg));
	(*T2_).Sup.Sup.Sup.m_type = (&NTIv2__ZtpkNCsFg9clzpeO8KwUyVg_);
	(*T2_).Sup.Sup.name = "AssertionDefect";
	blitTmp = message_p1;
	eqwasMoved___stdZassertions_u27((&message_p1));
	(*T2_).Sup.Sup.message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "AssertionDefect", "sysFatal", "fatal.nim", 53);
goto LA1_;
	{
		LA1_:;
	}
	{
		if (message_p1.p && !(message_p1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(message_p1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u40)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = eqdup___stdZassertions_u33(msg_p0);
	sysFatal__stdZassertions_u42(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u232)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	raiseAssert__stdZassertions_u40(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
