/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "string.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, burnMem__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZutils_u290)(void* p_p0, NI size_p1) {
	explicit_bzero(p_p0, ((size_t) (size_p1)));
}
