/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___5FAzRxBtxd6QVdIoguPw7Q tyObject_TimezonecolonObjectType___5FAzRxBtxd6QVdIoguPw7Q;
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___5FAzRxBtxd6QVdIoguPw7Q* utcInstance__pureZtimes_u1784;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___5FAzRxBtxd6QVdIoguPw7Q* localInstance__pureZtimes_u1785;
