/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI64, sum__winternitz_u1382)(NI64* x_p0, NI x_p0Len_0) {
	NI64 result;
{	result = (NI64)0;
	{
		NI64* i;
		NI i_2;
		i = (NI64*)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI64 TM__YqBQIdfvZX5pt75kDBsDLg_2;
				if (!(i_2 < x_p0Len_0)) goto LA3;
				if (i_2 < 0 || i_2 >= x_p0Len_0){ raiseIndexError2(i_2,x_p0Len_0-1); goto BeforeRet_;
				}
				i = (&x_p0[i_2]);
				if (nimAddInt64(result, (*i), &TM__YqBQIdfvZX5pt75kDBsDLg_2)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI64)(TM__YqBQIdfvZX5pt75kDBsDLg_2);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
