/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA;
typedef struct tyObject_RefHeader__rXRUb9cyZX0uazsgavSjpaA tyObject_RefHeader__rXRUb9cyZX0uazsgavSjpaA;
typedef struct tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg;
typedef struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content;
typedef struct tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA;
typedef struct tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA;
typedef struct tyObject_ArithmeticDefect__CWtXa5hjIqGz9bc4HDHkBqA tyObject_ArithmeticDefect__CWtXa5hjIqGz9bc4HDHkBqA;
typedef struct tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg;
typedef struct tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA;
typedef struct tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct tyObject_RefHeader__rXRUb9cyZX0uazsgavSjpaA {
	NI rc;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg {
  NI len; tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg trace;
	Exception* up;
};
struct tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw {
  Exception Sup;
};
struct tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA {
  tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw Sup;
};
struct tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA {
  tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw Sup;
};
struct tyObject_ArithmeticDefect__CWtXa5hjIqGz9bc4HDHkBqA {
  tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw Sup;
};
struct tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA {
  tyObject_ArithmeticDefect__CWtXa5hjIqGz9bc4HDHkBqA Sup;
};
struct tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg {
  tyObject_Defect__iG9a4ROmHK9aA9b9a54GXVLYfw Sup;
};
struct tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA {
  tyObject_ArithmeticDefect__CWtXa5hjIqGz9bc4HDHkBqA Sup;
};
struct tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg_Content { NI cap; tyObject_StackTraceEntry__DpnbnyBBFcQ6Xuzo9cwkcPg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3765)(tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u810)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u82)(tySequence__W9bYv2E9cYtJp9aZ9bNrzE3lqg dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3817)(tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4144)(tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u49)(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4193)(tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE TNimTypeV2 NTIv2__K9cWV3uS9cANrizntKonomBA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__G5jzFbMaKU3ct9a9cKn3mAcA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__BarUr4duoKe9cYnw1OyDkDA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__ZtpkNCsFg9clzpeO8KwUyVg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__GiWYBPBcWwaHQ481WrGAIA_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 1870152704, 4120239616};
N_LIB_PRIVATE TNimTypeV2 NTIv2__K9cWV3uS9cANrizntKonomBA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 1870152704, 2566067456};
N_LIB_PRIVATE TNimTypeV2 NTIv2__G5jzFbMaKU3ct9a9cKn3mAcA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[5] = {3701606400, 1285336064, 1870152704, 1800891136, 2866065152};
N_LIB_PRIVATE TNimTypeV2 NTIv2__BarUr4duoKe9cYnw1OyDkDA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 1870152704, 3664000000};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ZtpkNCsFg9clzpeO8KwUyVg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[5] = {3701606400, 1285336064, 1870152704, 1800891136, 630719488};
N_LIB_PRIVATE TNimTypeV2 NTIv2__GiWYBPBcWwaHQ481WrGAIA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NI, minuspercent___system_u810)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__rXRUb9cyZX0uazsgavSjpaA* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u810(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__rXRUb9cyZX0uazsgavSjpaA*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3765)(tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u82((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u3765(((tyObject_RangeDefect__K9cWV3uS9cANrizntKonomBA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3817)(tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u82((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u3817(((tyObject_IndexDefect__G5jzFbMaKU3ct9a9cKn3mAcA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4144)(tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u82((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4144(((tyObject_OverflowDefect__BarUr4duoKe9cYnw1OyDkDA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u49)(tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u82((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u49(((tyObject_AssertionDefect__ZtpkNCsFg9clzpeO8KwUyVg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4193)(tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u82((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4193(((tyObject_DivByZeroDefect__GiWYBPBcWwaHQ481WrGAIA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
