/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <cpuid.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU16 tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA;
typedef NU8 tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA;
typedef NU32 tyArray__FleBT9cC2nxhgiXmSYYnEKA[4];
N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA, getCpuFeatures__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u85)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, cpuId__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u22)(NU32 leaf_p0, NU32 subleaf_p1, tyArray__FleBT9cC2nxhgiXmSYYnEKA Result);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA nimcryptoCpuFeatures__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u138;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
N_LIB_PRIVATE N_NIMCALL(void, cpuId__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u22)(NU32 leaf_p0, NU32 subleaf_p1, tyArray__FleBT9cC2nxhgiXmSYYnEKA Result) {
	tyArray__FleBT9cC2nxhgiXmSYYnEKA res;
	NU32* T1_;
	NU32* T2_;
	NU32* T3_;
	NU32 T4_;
	nimZeroMem((void*)res, sizeof(tyArray__FleBT9cC2nxhgiXmSYYnEKA));
	T1_ = (NU32*)0;
	T1_ = (&res[(((NI)0))- 0]);
	T2_ = (NU32*)0;
	T2_ = (&res[(((NI)1))- 0]);
	T3_ = (NU32*)0;
	T3_ = (&res[(((NI)2))- 0]);
	T4_ = (NU32)0;
	T4_ = __get_cpuid_count(leaf_p0, subleaf_p1, T1_, T2_, T3_, (&res[(((NI)3))- 0]));
	(void)(T4_);
	nimCopyMem((void*)Result, (NIM_CONST void*)res, sizeof(tyArray__FleBT9cC2nxhgiXmSYYnEKA));
}
N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA, getCpuFeatures__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u85)(void) {
	tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA result;
	tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA res;
	tyArray__FleBT9cC2nxhgiXmSYYnEKA array1;
	tyArray__FleBT9cC2nxhgiXmSYYnEKA array7;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&res), sizeof(tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA));
	res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)0))) & 15);
	nimZeroMem((void*)array1, sizeof(tyArray__FleBT9cC2nxhgiXmSYYnEKA));
	cpuId__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u22(((NU32)1), ((NU32)0), array1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)array7, sizeof(tyArray__FleBT9cC2nxhgiXmSYYnEKA));
	cpuId__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u22(((NU32)7), ((NU32)0), array7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!(((NU32)(array1[(((NI)2))- 0] & ((NU32)268435456)) == ((NU32)0)))) goto LA3_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)2))) & 15);
	}
LA3_: ;
	{
		if (!!(((NU32)(array1[(((NI)2))- 0] & ((NU32)33554432)) == ((NU32)0)))) goto LA7_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)9))) & 15);
	}
LA7_: ;
	{
		if (!!(((NU32)(array1[(((NI)2))- 0] & ((NU32)1048576)) == ((NU32)0)))) goto LA11_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)8))) & 15);
	}
LA11_: ;
	{
		if (!!(((NU32)(array7[(((NI)1))- 0] & ((NU32)536870912)) == ((NU32)0)))) goto LA15_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)5))) & 15);
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)6))) & 15);
	}
LA15_: ;
	{
		if (!!(((NU32)(array7[(((NI)1))- 0] & ((NU32)32)) == ((NU32)0)))) goto LA19_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)3))) & 15);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = !(((NU32)(array7[(((NI)1))- 0] & ((NU32)65536)) == ((NU32)0)));
		if (!(T23_)) goto LA24_;
		T23_ = !(((NU32)(array7[(((NI)1))- 0] & ((NU32)1073741824)) == ((NU32)0)));
LA24_: ;
		if (!T23_) goto LA25_;
		res |= ((NU16)1)<<(((((tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA)4))) & 15);
	}
LA25_: ;
	result = res;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatscpufeaturesdotnim_Init000)(void) {
{
	tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA T1_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tySet_tyEnum_CpuFeature__9cD8SKzdjy9aVGMYgyk5wmxA));
	T1_ = getCpuFeatures__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u85();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimcryptoCpuFeatures__OOZOOZOOZOOZOOZOnimbleZpkgs50Znimcrypto4548O55O5145f5550b5748fe51f52da4857efa525650de52f56555057e55ee52abea50fZnimcryptoZcpufeatures_u138 = T1_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

