/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/syscall.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef int tyArray__bpgyACnpuq1ETodMD6DE5w[2];
static N_INLINE(NI, urandomInternalImpl__stdZsysrand_u18)(NU8* dest_p0, NI dest_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u232)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL, contains__stdZsysrand_u40)(int* a_p0, NI a_p0Len_0, int item_p1);
static N_INLINE(NI, find__stdZsysrand_u45)(int* a_p0, NI a_p0Len_0, int item_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u99)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__sT0fWggTrXhnxQ79bl9a8nHg_3 = { 28 | NIM_STRLIT_FLAG, "sysrand.nim(195, 9) `false` " };
static const NimStringV2 TM__sT0fWggTrXhnxQ79bl9a8nHg_4 = {28, (NimStrPayload*)&TM__sT0fWggTrXhnxQ79bl9a8nHg_3};
static NIM_CONST tyArray__bpgyACnpuq1ETodMD6DE5w TM__sT0fWggTrXhnxQ79bl9a8nHg_7 = {((int)4),
((int)11)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(NI, find__stdZsysrand_u45)(int* a_p0, NI a_p0Len_0, int item_p1) {
	NI result;
{	result = ((NI)0);
	{
		int* i;
		NI i_2;
		i = (int*)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__sT0fWggTrXhnxQ79bl9a8nHg_6;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i = (&a_p0[i_2]);
				{
					if (!((*i) == item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				if (nimAddInt(result, ((NI)1), &TM__sT0fWggTrXhnxQ79bl9a8nHg_6)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_6);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZsysrand_u40)(int* a_p0, NI a_p0Len_0, int item_p1) {
	NIM_BOOL result;
	NI T1_;
{	T1_ = (NI)0;
	T1_ = find__stdZsysrand_u45(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
static N_INLINE(NI, urandomInternalImpl__stdZsysrand_u18)(NU8* dest_p0, NI dest_p0Len_0) {
	NI result;
	NI sizeX60gensym1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	sizeX60gensym1_ = dest_p0Len_0;
	{
		if (!(sizeX60gensym1_ == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		while (1) {
			NI readBytesX60gensym1_;
			NI TM__sT0fWggTrXhnxQ79bl9a8nHg_2;
			if (!(result < sizeX60gensym1_)) goto LA6;
			if (result < 0 || result >= dest_p0Len_0){ raiseIndexError2(result,dest_p0Len_0-1); goto BeforeRet_;
			}
			if (nimSubInt(sizeX60gensym1_, result, &TM__sT0fWggTrXhnxQ79bl9a8nHg_2)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_2)) < ((int)(-2147483647 -1)) || ((NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_2)) > ((int)2147483647)){ raiseRangeErrorI((NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_2), ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
			}
			readBytesX60gensym1_ = syscall(SYS_getrandom, (&dest_p0[result]), ((int) ((NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_2))), ((NI)0));
			{
				if (!(readBytesX60gensym1_ == ((NI)0))) goto LA9_;
				{
					if (!NIM_TRUE) goto LA13_;
					failedAssertImpl__stdZassertions_u232(TM__sT0fWggTrXhnxQ79bl9a8nHg_4);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			}
			goto LA7_;
LA9_: ;
			{
				NI TM__sT0fWggTrXhnxQ79bl9a8nHg_5;
				if (!(((NI)0) < readBytesX60gensym1_)) goto LA16_;
				if (nimAddInt(result, readBytesX60gensym1_, &TM__sT0fWggTrXhnxQ79bl9a8nHg_5)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__sT0fWggTrXhnxQ79bl9a8nHg_5);
			}
			goto LA7_;
LA16_: ;
			{
				{
					NI32 T21_;
					NIM_BOOL T22_;
					T21_ = (NI32)0;
					T21_ = osLastError__stdZoserrors_u99();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T22_ = (NIM_BOOL)0;
					T22_ = contains__stdZsysrand_u40(TM__sT0fWggTrXhnxQ79bl9a8nHg_7, 2, T21_);
					if (!T22_) goto LA23_;
				}
				goto LA19_;
LA23_: ;
				{
					result = ((NI)-1);
					goto LA5;
				}
LA19_: ;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, urandom__stdZsysrand_u117)(NU8* dest_p0, NI dest_p0Len_0) {
	NIM_BOOL result;
	NI ret;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_TRUE;
	ret = urandomInternalImpl__stdZsysrand_u18(dest_p0, dest_p0Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(ret < ((NI)0))) goto LA3_;
		result = NIM_FALSE;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
