/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, reverse__winternitz_u1346)(NU8* a_p0, NI a_p0Len_0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
N_LIB_PRIVATE N_NIMCALL(void, reverse__winternitz_u1346)(NU8* a_p0, NI a_p0Len_0, NI first_p1, NI last_p2) {
	NI x;
	NI y;
{	x = first_p1;
	y = last_p2;
	{
		while (1) {
			NU8 T3_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_3;
			if (!(((NI) (x)) < ((NI) (y)))) goto LA2;
			T3_ = (NU8)0;
			if (x < 0 || x >= a_p0Len_0){ raiseIndexError2(x,a_p0Len_0-1); goto BeforeRet_;
			}
			if (y < 0 || y >= a_p0Len_0){ raiseIndexError2(y,a_p0Len_0-1); goto BeforeRet_;
			}
			T3_ = a_p0[x];
			a_p0[x] = a_p0[y];
			a_p0[y] = T3_;
			if (nimSubInt(y, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JdC9c6SaUkvO1XjYuWP1JWQ_2 < 0 || TM__JdC9c6SaUkvO1XjYuWP1JWQ_2 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			y = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2);
			if (nimAddInt(x, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_3)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JdC9c6SaUkvO1XjYuWP1JWQ_3 < 0 || TM__JdC9c6SaUkvO1XjYuWP1JWQ_3 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			x = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_3);
		} LA2: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, reverse__winternitz_u1340)(NU8* a_p0, NI a_p0Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if ((((((NI)0) >= (a_p0Len_0-1)) ? ((NI)0) : (a_p0Len_0-1))) < ((NI)0) || (((((NI)0) >= (a_p0Len_0-1)) ? ((NI)0) : (a_p0Len_0-1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((((NI)0) >= (a_p0Len_0-1)) ? ((NI)0) : (a_p0Len_0-1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	reverse__winternitz_u1346(a_p0, a_p0Len_0, ((NI)0), ((NI) (((((NI)0) >= (a_p0Len_0-1)) ? ((NI)0) : (a_p0Len_0-1)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
