/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Rand__qdzrpqe42uih1y77c6iGTg tyObject_Rand__qdzrpqe42uih1y77c6iGTg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q;
struct tyObject_Rand__qdzrpqe42uih1y77c6iGTg {
	NU64 a0;
	NU64 a1;
};
typedef long tyArray__B71stzPvuTXMbmiYmn9brGQ[5];
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU64 tyArray__NzKR9bw29cLPrd712Xt6Liiw[2];
struct tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q {
	NI a;
	NI b;
};
typedef int tyArray__Pk9c8DhUOqt8r9aBvHyrLtnw[1];
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__qdzrpqe42uih1y77c6iGTg, initRand__pureZrandom_u303)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(void, acquire__coreZlocks_u14)(pthread_mutex_t* lock_p0);
static N_INLINE(NIM_BOOL, isValid__pureZrandom_u16)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg r_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__qdzrpqe42uih1y77c6iGTg, getRandomState__pureZrandom_u305)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, urandom__stdZsysrand_u117)(NU8* dest_p0, NI dest_p0Len_0);
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u6992)(NimStringV2 errormsg_p0, NI errorcode_p1);
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_u45)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0);
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1);
static N_INLINE(void, release__coreZlocks_u16)(pthread_mutex_t* lock_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rand__winternitz_u34)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0, tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q x_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u232)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NU, rand__winternitz_u45)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0, NU max_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[81+1];
} TM__AIKkgex03Z1j45JceakCTA_3 = { 81 | NIM_STRLIT_FLAG, "Failed to initializes baseState in random module as sysrand.urandom doesn\'t work." };
static const NimStringV2 TM__AIKkgex03Z1j45JceakCTA_4 = {81, (NimStrPayload*)&TM__AIKkgex03Z1j45JceakCTA_3};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__AIKkgex03Z1j45JceakCTA_7 = { 32 | NIM_STRLIT_FLAG, "random.nim(339, 3) `x.a <= x.b` " };
static const NimStringV2 TM__AIKkgex03Z1j45JceakCTA_8 = {32, (NimStrPayload*)&TM__AIKkgex03Z1j45JceakCTA_7};
N_LIB_PRIVATE NIM_CONST tyObject_Rand__qdzrpqe42uih1y77c6iGTg DefaultRandSeed__pureZrandom_u14 = {7616934476015405061ULL, 15122295919272093642ULL}
;
N_LIB_PRIVATE NIM_CONST tyArray__NzKR9bw29cLPrd712Xt6Liiw helper__pureZrandom_u47 = {13739361407582206667ULL,
15594563132006766882ULL}
;
N_LIB_PRIVATE tyObject_Rand__qdzrpqe42uih1y77c6iGTg state__pureZrandom_u15;
N_LIB_PRIVATE pthread_mutex_t baseSeedLock__pureZrandom_u301;
N_LIB_PRIVATE tyObject_Rand__qdzrpqe42uih1y77c6iGTg baseState__pureZrandom_u302;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0) {
	pthread_mutex_init(((pthread_mutex_t*) (lock_p0)), ((pthread_mutexattr_t*) (((pthread_mutexattr_t*) NIM_NIL))));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, acquire__coreZlocks_u14)(pthread_mutex_t* lock_p0) {
	pthread_mutex_lock(((pthread_mutex_t*) (lock_p0)));
}
static N_INLINE(NIM_BOOL, isValid__pureZrandom_u16)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg r_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (r_p0.a0 == 0ULL);
	if (!(T1_)) goto LA2_;
	T1_ = (r_p0.a1 == 0ULL);
LA2_: ;
	result = !(T1_);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__qdzrpqe42uih1y77c6iGTg, getRandomState__pureZrandom_u305)(void) {
	tyObject_Rand__qdzrpqe42uih1y77c6iGTg result;
	tyArray__qtqsWM5aXmcpMIVmvq3kAA urand;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__qdzrpqe42uih1y77c6iGTg));
	nimZeroMem((void*)urand, sizeof(tyArray__qtqsWM5aXmcpMIVmvq3kAA));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				NI TM__AIKkgex03Z1j45JceakCTA_2;
				if (!(res <= ((NI)7))) goto LA3;
				i = ((NI) (res));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = urandom__stdZsysrand_u117(urand, 16);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					copyMem__system_u1745(((void*) ((&result))), ((void*) ((&urand[(((NI)0))- 0]))), ((NI)16));
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = isValid__pureZrandom_u16(result);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T11_) goto LA12_;
						goto LA1;
					}
LA12_: ;
				}
LA7_: ;
				if (nimAddInt(res, ((NI)1), &TM__AIKkgex03Z1j45JceakCTA_2)) { raiseOverflow(); goto BeforeRet_;
				};
				res = (NI)(TM__AIKkgex03Z1j45JceakCTA_2);
			} LA3: ;
		}
	} LA1: ;
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = isValid__pureZrandom_u16(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T16_)) goto LA17_;
		quit__system_u6992(TM__AIKkgex03Z1j45JceakCTA_4, ((NI)1));
	}
LA17_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1) {
	NU64 result;
	result = (NU64)((NU64)((NU64)(x_p0) << (NU64)(k_p1)) | (NU64)((NU64)(x_p0) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k_p1)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0) {
	NU64 result;
	NU64 s0;
	NU64 s1;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0 = (*r_p0).a0;
	s1 = (*r_p0).a1;
	result = (NU64)((NU64)(s0) + (NU64)(s1));
	s1 = (NU64)(s1 ^ s0);
	T1_ = (NU64)0;
	T1_ = rotl__pureZrandom_u24(s0, 55ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a0 = (NU64)((NU64)(T1_ ^ s1) ^ (NU64)((NU64)(s1) << (NU64)(((NI)14))));
	T2_ = (NU64)0;
	T2_ = rotl__pureZrandom_u24(s1, 36ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a1 = T2_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_u45)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* s_p0) {
	NU64 s0;
	NU64 s1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0 = 0ULL;
	s1 = 0ULL;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI)0);
		{
			while (1) {
				NI TM__AIKkgex03Z1j45JceakCTA_6;
				if (!(res <= ((NI)1))) goto LA3;
				i = ((NI) (res));
				{
					NI b;
					NI i_2;
					b = (NI)0;
					i_2 = ((NI)0);
					{
						while (1) {
							NU64 T11_;
							NI TM__AIKkgex03Z1j45JceakCTA_5;
							if (!(i_2 < ((NI)64))) goto LA6;
							b = i_2;
							{
								if ((NU)(i) > (NU)(1)){ raiseIndexError2(i, 1); goto BeforeRet_;
								}
								if (!!(((NU64)(helper__pureZrandom_u47[(i)- 0] & (NU64)((NU64)(1ULL) << (NU64)(((NU64) (b))))) == 0ULL))) goto LA9_;
								s0 = (NU64)(s0 ^ (*s_p0).a0);
								s1 = (NU64)(s1 ^ (*s_p0).a1);
							}
LA9_: ;
							T11_ = (NU64)0;
							T11_ = next__pureZrandom_u36(s_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							(void)(T11_);
							if (nimAddInt(i_2, ((NI)1), &TM__AIKkgex03Z1j45JceakCTA_5)) { raiseOverflow(); goto BeforeRet_;
							};
							i_2 = (NI)(TM__AIKkgex03Z1j45JceakCTA_5);
						} LA6: ;
					}
				}
				if (nimAddInt(res, ((NI)1), &TM__AIKkgex03Z1j45JceakCTA_6)) { raiseOverflow(); goto BeforeRet_;
				};
				res = (NI)(TM__AIKkgex03Z1j45JceakCTA_6);
			} LA3: ;
		}
	}
	(*s_p0).a0 = s0;
	(*s_p0).a1 = s1;
	}BeforeRet_: ;
}
static N_INLINE(void, release__coreZlocks_u16)(pthread_mutex_t* lock_p0) {
	pthread_mutex_unlock(((pthread_mutex_t*) (lock_p0)));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__qdzrpqe42uih1y77c6iGTg, initRand__pureZrandom_u303)(void) {
	tyObject_Rand__qdzrpqe42uih1y77c6iGTg result;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__qdzrpqe42uih1y77c6iGTg));
	acquire__coreZlocks_u14(((pthread_mutex_t*) ((&baseSeedLock__pureZrandom_u301))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T4_;
		tyObject_Rand__qdzrpqe42uih1y77c6iGTg T7_;
		T4_ = (NIM_BOOL)0;
		T4_ = isValid__pureZrandom_u16(baseState__pureZrandom_u302);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		nimZeroMem((void*)(&T7_), sizeof(tyObject_Rand__qdzrpqe42uih1y77c6iGTg));
		T7_ = getRandomState__pureZrandom_u305();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		baseState__pureZrandom_u302 = T7_;
	}
LA5_: ;
	result = baseState__pureZrandom_u302;
	skipRandomNumbers__pureZrandom_u45((&baseState__pureZrandom_u302));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		release__coreZlocks_u16(((pthread_mutex_t*) ((&baseSeedLock__pureZrandom_u301))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u349)(void) {
	tyObject_Rand__qdzrpqe42uih1y77c6iGTg T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Rand__qdzrpqe42uih1y77c6iGTg));
	T1_ = initRand__pureZrandom_u303();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	state__pureZrandom_u15 = T1_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU, rand__winternitz_u45)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0, NU max_p1) {
	NU result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU)0;
	{
		if (!(max_p1 == ((NU)0))) goto LA3_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NU64 max_2;
		NI iters;
		max_2 = ((NU64) (max_p1));
		{
			NU64 T10_;
			if (!(max_2 == 18446744073709551615ULL)) goto LA8_;
			T10_ = (NU64)0;
			T10_ = next__pureZrandom_u36(r_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = ((NU) (T10_));
			goto BeforeRet_;
		}
LA8_: ;
		iters = ((NI)0);
		{
			while (1) {
				NU64 x;
				x = next__pureZrandom_u36(r_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					NIM_BOOL T15_;
					T15_ = (NIM_BOOL)0;
					T15_ = ((NU64)(x) <= (NU64)((NU64)((NU64)(18446744073709551615ULL) - (NU64)((NU64)((NU64)(18446744073709551615ULL) % (NU64)(max_2))))));
					if (T15_) goto LA16_;
					T15_ = (((NI)20) < iters);
LA16_: ;
					if (!T15_) goto LA17_;
					result = ((NU) ((NU64)((NU64)(x) % (NU64)((NU64)((NU64)(max_2) + (NU64)(1ULL))))));
					goto BeforeRet_;
				}
				goto LA13_;
LA17_: ;
				{
					NI TM__AIKkgex03Z1j45JceakCTA_9;
					if (nimAddInt(iters, ((NI)1), &TM__AIKkgex03Z1j45JceakCTA_9)) { raiseOverflow(); goto BeforeRet_;
					};
					iters = (NI)(TM__AIKkgex03Z1j45JceakCTA_9);
				}
LA13_: ;
			}
		}
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__winternitz_u34)(tyObject_Rand__qdzrpqe42uih1y77c6iGTg* r_p0, tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q x_p1) {
	NI result;
	NU T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!!((x_p1.a <= x_p1.b))) goto LA3_;
		failedAssertImpl__stdZassertions_u232(TM__AIKkgex03Z1j45JceakCTA_8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	T5_ = (NU)0;
	T5_ = rand__winternitz_u45(r_p0, (NU)((NU64)(((NU) (x_p1.b))) - (NU64)(((NU) (x_p1.a)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) ((NU)((NU64)(T5_) + (NU64)(((NU) (x_p1.a))))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__winternitz_u26)(tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q x_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = rand__winternitz_u34((&state__pureZrandom_u15), x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatspureatsrandomdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	state__pureZrandom_u15 = DefaultRandSeed__pureZrandom_u14;
	initLock__coreZlocks_u7(((pthread_mutex_t*) ((&baseSeedLock__pureZrandom_u301))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

