/* Generated by Nim Compiler v2.0.8 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg tySequence__aLjCOs9bu5l2rz6ENM6m6Sg;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q;
typedef struct tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ tySequence__IHUFRsFxZNv7YydiUO2esQ;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content tySequence__IHUFRsFxZNv7YydiUO2esQ_Content;
struct tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ {
	NU8* privateKey;
	NU8* publicKey;
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg {
  NI len; tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q {
	NI a;
	NI b;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q {
NIM_ALIGN(16) 	tyArray__vEOa9c5qaE9ajWxR5R4zwfQg data;
};
typedef NU8 tyUncheckedArray__nMUrxcwM7yrVbfFpM3W4Sw[1];
struct tySequence__IHUFRsFxZNv7YydiUO2esQ {
  NI len; tySequence__IHUFRsFxZNv7YydiUO2esQ_Content* p;
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content { NI cap; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content { NI cap; NI64 data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ, generate_keypair)(NI n_p0, NI w_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_u1763)(NI size_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg, newSeq__winternitz_u950)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, generate_random_bytes__winternitz_u9)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* address_p0, NI length_p1);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u349)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZtimes_u2296)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8 y_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rand__winternitz_u26)(tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q x_p0);
static N_INLINE(tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2347)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, hash_bytes__winternitz_u74)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* source_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p1, NI length_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, X5BX5D___winternitz_u100)(NU8* s_p0, NI s_p0Len_0, tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q x_p1);
N_LIB_PRIVATE N_NIMCALL(void, digest__winternitz_u121)(NU8* dataX60gensym15__p1, NI dataX60gensym15__p1Len_0, tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q* Result);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__stdZsysrand_u136)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__winternitz_u802)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8* y_p1, NI y_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2338)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___winternitz_u961)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg dest_p0);
N_LIB_EXPORT N_CDECL(NU8*, sign)(NU8* message_p0, NU8* secret_key_p1, NI n_p2, NI w_p3);
N_LIB_PRIVATE N_NIMCALL(NU8*, sign__winternitz_u1368)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, tySequence__aLjCOs9bu5l2rz6ENM6m6Sg secret_key_p1, NI n_p2, NI w_p3);
N_LIB_PRIVATE N_NIMCALL(tySequence__IHUFRsFxZNv7YydiUO2esQ, split__winternitz_u1039)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, NI w_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__winternitz_u1069)(tySequence__IHUFRsFxZNv7YydiUO2esQ* x_p0, NI64 y_p1);
N_LIB_PRIVATE N_NIMCALL(NI64, sum__winternitz_u1382)(NI64* x_p0, NI x_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, add__winternitz_u1417)(tySequence__IHUFRsFxZNv7YydiUO2esQ* x_p0, NI64* y_p1, NI y_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, to_bytes__winternitz_u1307)(NI64 value_p0, NI c_p1);
N_LIB_PRIVATE N_NIMCALL(void, reverse__winternitz_u1340)(NU8* a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___winternitz_u1185)(tySequence__IHUFRsFxZNv7YydiUO2esQ dest_p0);
N_LIB_EXPORT N_CDECL(NIM_BOOL, verify)(NU8* message_p0, NU8* signature_p1, NU8* public_key_p2, NI n_p3, NI w_p4);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, verify__winternitz_u1537)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ signature_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ public_key_p2, NI n_p3, NI w_p4);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___winternitz_u1603)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatspureatsrandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatscpufeaturesdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatssha2atssha2_avxdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatssha2atssha2dotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3519;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3519);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == ((NI)(IL64(-9223372036854775807) - IL64(1))));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == ((NI)-1));
LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA5_: ;
	{
		(*res_p2) = (NI)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, generate_random_bytes__winternitz_u9)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* address_p0, NI length_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	randomize__pureZrandom_u349();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NU8 colontmpD_;
				tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q T4_;
				NI T5_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_8;
				if (!(i_2 < length_p1)) goto LA3;
				colontmpD_ = (NU8)0;
				i = i_2;
				T4_ = dotdot___stdZstrbasics_u48(((NI)0), ((NI)255));
				T5_ = (NI)0;
				T5_ = rand__winternitz_u26(T4_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				colontmpD_ = ((NU8) (T5_));
				add__pureZtimes_u2296(address_p0, colontmpD_);
				if (nimAddInt(i_2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_8)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_8);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
N_LIB_PRIVATE N_NIMCALL(void, hash_bytes__winternitz_u74)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* source_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p1, NI length_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI i;
		NI colontmp_;
		NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_11;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(length_p2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_11)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_11);
		res = ((NI)0);
		{
			while (1) {
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ chunk;
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ hash;
				NI chunkSize;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_12;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_13;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_14;
				tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q T5_;
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T6_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_16;
				if (!(res <= colontmp_)) goto LA3;
				chunk.len = 0; chunk.p = NIM_NIL;
				hash.len = 0; hash.p = NIM_NIL;
				i = ((NI) (res));
				if (nimSubInt(length_p2, i, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_12)) { raiseOverflow(); goto LA4_;
				};
				chunkSize = ((((NI)32) <= (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_12)) ? ((NI)32) : (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_12));
				if (nimAddInt(i, chunkSize, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_13)) { raiseOverflow(); goto LA4_;
				};
				if (nimSubInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_13), ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_14)) { raiseOverflow(); goto LA4_;
				};
				T5_ = dotdot___stdZstrbasics_u48(i, (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_14));
				chunk = X5BX5D___winternitz_u100((((*source_p0)).p) ? ((*source_p0).p->data) : NIM_NIL, (*source_p0).len, T5_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				T6_.len = 0; T6_.p = NIM_NIL;
				{
					tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resultX60gensym35_;
					tyArray__vEOa9c5qaE9ajWxR5R4zwfQg colontmp__2;
					tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q T9_;
					NI iX60gensym35_;
					resultX60gensym35_.len = 0; resultX60gensym35_.p = NIM_NIL;
					nimZeroMem((void*)colontmp__2, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
					nimZeroMem((void*)(&T9_), sizeof(tyObject_MDigest__vgesnavuwl8RX6BxrouH1Q));
					digest__winternitz_u121(((chunk).p) ? (chunk.p->data) : NIM_NIL, chunk.len, (&T9_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					nimCopyMem((void*)colontmp__2, (NIM_CONST void*)T9_.data, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
					iX60gensym35_ = ((NI)0);
					resultX60gensym35_ = newSeq__stdZsysrand_u136(((NI)32));
					{
						NU8 itX60gensym35_;
						NI i_2;
						itX60gensym35_ = (NU8)0;
						i_2 = ((NI)0);
						{
							while (1) {
								NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_15;
								itX60gensym35_ = colontmp__2[(i_2)- 0];
								if (iX60gensym35_ < 0 || iX60gensym35_ >= resultX60gensym35_.len){ raiseIndexError2(iX60gensym35_,resultX60gensym35_.len-1); goto LA8_;
								}
								resultX60gensym35_.p->data[iX60gensym35_] = itX60gensym35_;
								if (nimAddInt(iX60gensym35_, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_15)) { raiseOverflow(); goto LA8_;
								};
								iX60gensym35_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_15);
								{
									if (!(((NI)31) <= ((NI) (i_2)))) goto LA15_;
									goto LA11;
								}
LA15_: ;
								i_2 += ((NI)1);
							}
						} LA11: ;
					}
					hash = resultX60gensym35_;
					{
						LA8_:;
					}
					{
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				}
				add__winternitz_u802(dest_p1, ((hash).p) ? (hash.p->data) : NIM_NIL, hash.len);
				if (nimAddInt(res, ((NI)32), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_16)) { raiseOverflow(); goto LA4_;
				};
				res = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_16);
				{
					LA4_:;
				}
				{
					eqdestroy___pureZtimes_u2338(hash);
					eqdestroy___pureZtimes_u2338(chunk);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(void, copyMem__system_u1745)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_EXPORT N_CDECL(tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ, generate_keypair)(NI n_p0, NI w_p1) {
	tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ result;
	tySequence__aLjCOs9bu5l2rz6ENM6m6Sg privateKey;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ publicKey;
	NU8* colontmpD_;
	NU8* colontmpD__2;
	NI a;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_2;
	NI pow_w;
	NI c;
	NF T1_;
	NF T2_;
	void* rawPrivateKey;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_3;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_4;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5;
	void* rawPublicKey;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_6;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_9;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_10;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_22;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_23;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_24;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_WinternitzKeyPair__jBc87gyNTnvJQspxETMKvQ));
	privateKey.len = 0; privateKey.p = NIM_NIL;
	publicKey.len = 0; publicKey.p = NIM_NIL;
	colontmpD_ = (NU8*)0;
	colontmpD__2 = (NU8*)0;
	if (w_p1 == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(n_p0, w_p1, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_2)) { raiseOverflow(); goto BeforeRet_;
	};
	a = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_2);
	pow_w = (NI)((NU64)(((NI)1)) << (NU64)(w_p1));
	T1_ = (NF)0;
	T1_ = log2(((NF)(((NF) (a))) * (NF)(((NF)(((NF) (pow_w))) - (NF)(1.0)))));
	T2_ = (NF)0;
	T2_ = ceil(((NF)(T1_) / (NF)(((NF) (w_p1)))));
	c = ((NI) (T2_));
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_3)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)((n_p0) / (((NI)8))), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_3), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_4)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_4), pow_w, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	rawPrivateKey = alloc0Impl__system_u1763(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_5))));
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)((n_p0) / (((NI)8))), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_6), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	rawPublicKey = alloc0Impl__system_u1763(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_7))));
	if ((pow_w) < ((NI)0) || (pow_w) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pow_w, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	privateKey = newSeq__winternitz_u950(((NI) (pow_w)));
	publicKey.len = 0; publicKey.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	if (((NI)0) < 0 || ((NI)0) >= privateKey.len){ raiseIndexError2(((NI)0),privateKey.len-1); goto BeforeRet_;
	}
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_9)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)((n_p0) / (((NI)8))), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_9), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_10)) { raiseOverflow(); goto BeforeRet_;
	};
	generate_random_bytes__winternitz_u9((&privateKey.p->data[((NI)0)]), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_10));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI)1);
		{
			while (1) {
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T6_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17;
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* T7_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_18;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_19;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_20;
				if (!(i_2 < pow_w)) goto LA5;
				i = i_2;
				if (i < 0 || i >= privateKey.len){ raiseIndexError2(i,privateKey.len-1); goto BeforeRet_;
				}
				T6_.len = 0; T6_.p = NIM_NIL;
				T6_.len = 0; T6_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
				eqsink___pureZtimes_u2347((&privateKey.p->data[i]), T6_);
				if (nimSubInt(i, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17) < 0 || (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17) >= privateKey.len){ raiseIndexError2((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17),privateKey.len-1); goto BeforeRet_;
				}
				T7_ = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*)0;
				T7_ = (&privateKey.p->data[(NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_17)]);
				if (i < 0 || i >= privateKey.len){ raiseIndexError2(i,privateKey.len-1); goto BeforeRet_;
				}
				if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_18)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_18), (NI)((n_p0) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_19)) { raiseOverflow(); goto BeforeRet_;
				};
				hash_bytes__winternitz_u74(T7_, (&privateKey.p->data[i]), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_19));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(i_2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_20)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_20);
			} LA5: ;
		}
	}
	if (nimSubInt(pow_w, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21) < 0 || (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21) >= privateKey.len){ raiseIndexError2((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21),privateKey.len-1); goto BeforeRet_;
	}
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_22)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_22), (NI)((n_p0) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_23)) { raiseOverflow(); goto BeforeRet_;
	};
	hash_bytes__winternitz_u74((&privateKey.p->data[(NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_21)]), (&publicKey), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_23));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (((NI)0) < 0 || ((NI)0) >= publicKey.len){ raiseIndexError2(((NI)0),publicKey.len-1); goto BeforeRet_;
	}
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_24)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_24), (NI)((n_p0) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1745(rawPublicKey, ((void*) ((&publicKey.p->data[((NI)0)]))), ((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_25))));
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		i_4 = ((NI)0);
		{
			while (1) {
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_32;
				if (!(i_4 < pow_w)) goto LA10;
				i_3 = i_4;
				{
					NI j;
					NI colontmp_;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_26;
					NI i_5;
					j = (NI)0;
					colontmp_ = (NI)0;
					if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_26)) { raiseOverflow(); goto BeforeRet_;
					};
					colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_26);
					i_5 = ((NI)0);
					{
						while (1) {
							NU offset;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_27;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_28;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_29;
							void* dest;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_31;
							if (!(i_5 < colontmp_)) goto LA13;
							j = i_5;
							if (nimMulInt(j, pow_w, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_27)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_27), i_3, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_28)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_28), (NI)((n_p0) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_29)) { raiseOverflow(); goto BeforeRet_;
							};
							offset = ((NU) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_29)));
							dest = ((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (rawPrivateKey))) + (NU64)(offset))));
							if (i_3 < 0 || i_3 >= privateKey.len){ raiseIndexError2(i_3,privateKey.len-1); goto BeforeRet_;
							}
							if (nimMulInt(j, (NI)((n_p0) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30) < 0 || (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30) >= privateKey.p->data[i_3].len){ raiseIndexError2((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30),privateKey.p->data[i_3].len-1); goto BeforeRet_;
							}
							if (((NI)((n_p0) / (((NI)8)))) < ((NI)0) || ((NI)((n_p0) / (((NI)8)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_p0) / (((NI)8))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
							}
							copyMem__system_u1745(dest, ((void*) ((&privateKey.p->data[i_3].p->data[(NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_30)]))), ((NI) ((NI)((n_p0) / (((NI)8))))));
							if (nimAddInt(i_5, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_31)) { raiseOverflow(); goto BeforeRet_;
							};
							i_5 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_31);
						} LA13: ;
					}
				}
				if (nimAddInt(i_4, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_32)) { raiseOverflow(); goto BeforeRet_;
				};
				i_4 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_32);
			} LA10: ;
		}
	}
	colontmpD_ = ((NU8*) (rawPrivateKey));
	result.privateKey = colontmpD_;
	colontmpD__2 = ((NU8*) (rawPublicKey));
	result.publicKey = colontmpD__2;
	eqdestroy___pureZtimes_u2338(publicKey);
	eqdestroy___winternitz_u961(privateKey);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__IHUFRsFxZNv7YydiUO2esQ, split__winternitz_u1039)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, NI w_p1) {
	tySequence__IHUFRsFxZNv7YydiUO2esQ result;
{	result.len = 0; result.p = (tySequence__IHUFRsFxZNv7YydiUO2esQ_Content*) newSeqPayload(0, sizeof(NI64), NIM_ALIGNOF(NI64));
	{
		if (!(w_p1 < ((NI)8))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI colontmp__2;
			NI T6_;
			NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_42;
			NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_43;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp__2 = (NI)0;
			T6_ = message_p0.len;
			if (nimMulInt(T6_, ((NI)8), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_42)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_42), ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_43)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_43);
			if ((w_p1) < ((NI)1) || (w_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(w_p1, ((NI)1), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmp__2 = ((NI) (w_p1));
			res = ((NI)0);
			{
				while (1) {
					NI current_byte_index;
					NI current_bit;
					NIM_BOOL requires_next_byte;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_44;
					NI remainder;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_45;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_46;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_51;
					if (!(res <= colontmp_)) goto LA8;
					i = ((NI) (res));
					current_byte_index = (NI)((i) / (((NI)8)));
					current_bit = (NI)((i) % (((NI)8)));
					if (nimSubInt(((NI)8), current_bit, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_44)) { raiseOverflow(); goto BeforeRet_;
					};
					requires_next_byte = ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_44) < w_p1);
					if (nimAddInt(current_bit, w_p1, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_45)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(((NI)8), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_45), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_46)) { raiseOverflow(); goto BeforeRet_;
					};
					remainder = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_46);
					{
						if (!requires_next_byte) goto LA11_;
						{
							NI T15_;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_47;
							NU8 mask;
							NU8 value;
							T15_ = message_p0.len;
							if (nimSubInt(T15_, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_47)) { raiseOverflow(); goto BeforeRet_;
							};
							if (!(current_byte_index == (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_47))) goto LA16_;
							mask = ((NU8) ((NI)((NI64)(((NI)255)) >> (NU64)(current_bit))));
							if (current_byte_index < 0 || current_byte_index >= message_p0.len){ raiseIndexError2(current_byte_index,message_p0.len-1); goto BeforeRet_;
							}
							value = (NU8)(message_p0.p->data[current_byte_index] & mask);
							add__winternitz_u1069((&result), ((NI64) (value)));
						}
						goto LA13_;
LA16_: ;
						{
							NU8 mask1;
							NU8 mask2;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_48;
							NU8 value1;
							NU8 value2;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_50;
							mask1 = ((NU8) ((NI)((NI64)(((NI)255)) >> (NU64)(current_bit))));
							if (nimAddInt(((NI)8), remainder, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_48)) { raiseOverflow(); goto BeforeRet_;
							};
							mask2 = ((NU8) ((NI)((NU64)(((NI)255)) << (NU64)((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_48)))));
							if (current_byte_index < 0 || current_byte_index >= message_p0.len){ raiseIndexError2(current_byte_index,message_p0.len-1); goto BeforeRet_;
							}
							if (remainder == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
							}
							value1 = (NU8)((NU64)((NU8)(message_p0.p->data[current_byte_index] & mask1)) << (NU64)((remainder > 0? (remainder) : -(remainder))));
							if (nimAddInt(current_byte_index, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49) < 0 || (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49) >= message_p0.len){ raiseIndexError2((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49),message_p0.len-1); goto BeforeRet_;
							}
							if (nimAddInt(((NI)8), remainder, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_50)) { raiseOverflow(); goto BeforeRet_;
							};
							value2 = (NU8)((NU8)((NU8)(message_p0.p->data[(NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_49)] & mask2)) >> (NU64)((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_50)));
							add__winternitz_u1069((&result), (NI64)(((NI64) (value1)) | ((NI64) (value2))));
						}
LA13_: ;
					}
					goto LA9_;
LA11_: ;
					{
						NU8 mask_2;
						NU8 value_2;
						mask_2 = ((NU8) ((NI)((NI)((NI64)(((NI)255)) >> (NU64)(current_bit)) & (NI)((NU64)(((NI)255)) << (NU64)(remainder)))));
						if (current_byte_index < 0 || current_byte_index >= message_p0.len){ raiseIndexError2(current_byte_index,message_p0.len-1); goto BeforeRet_;
						}
						value_2 = (NU8)((NU8)((NU8)(message_p0.p->data[current_byte_index] & mask_2)) >> (NU64)(remainder));
						add__winternitz_u1069((&result), ((NI64) (value_2)));
					}
LA9_: ;
					if (nimAddInt(res, colontmp__2, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_51)) { raiseOverflow(); goto BeforeRet_;
					};
					res = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_51);
				} LA8: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		{
			NI i_2;
			NI colontmp__3;
			NI colontmp__4;
			NI T22_;
			NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_52;
			NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_53;
			NI res_2;
			i_2 = (NI)0;
			colontmp__3 = (NI)0;
			colontmp__4 = (NI)0;
			T22_ = message_p0.len;
			if (nimMulInt(T22_, ((NI)8), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_52)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_52), ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_53)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp__3 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_53);
			if ((w_p1) < ((NI)1) || (w_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(w_p1, ((NI)1), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmp__4 = ((NI) (w_p1));
			res_2 = ((NI)0);
			{
				while (1) {
					NI64 value_3;
					NI bits_collected;
					NI bit_pos;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_60;
					if (!(res_2 <= colontmp__3)) goto LA24;
					i_2 = ((NI) (res_2));
					value_3 = IL64(0);
					bits_collected = ((NI)0);
					bit_pos = i_2;
					{
						while (1) {
							NI byte_idx;
							NI bit_in_byte;
							NI available;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_54;
							NI take;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_55;
							NI shift;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_56;
							NU8 mask_3;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_57;
							NI64 extracted;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_58;
							NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_59;
							if (!(bits_collected < w_p1)) goto LA26;
							byte_idx = (NI)((bit_pos) / (((NI)8)));
							{
								NI T29_;
								T29_ = message_p0.len;
								if (!(T29_ <= byte_idx)) goto LA30_;
								goto LA25;
							}
LA30_: ;
							bit_in_byte = (NI)((bit_pos) % (((NI)8)));
							if (nimSubInt(((NI)8), bit_in_byte, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_54)) { raiseOverflow(); goto BeforeRet_;
							};
							available = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_54);
							if (nimSubInt(w_p1, bits_collected, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_55)) { raiseOverflow(); goto BeforeRet_;
							};
							take = ((available <= (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_55)) ? available : (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_55));
							if (nimSubInt(available, take, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_56)) { raiseOverflow(); goto BeforeRet_;
							};
							shift = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_56);
							if (nimSubInt((NI)((NU64)(((NI)1)) << (NU64)(take)), ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_57)) { raiseOverflow(); goto BeforeRet_;
							};
							mask_3 = ((NU8) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_57)));
							if (byte_idx < 0 || byte_idx >= message_p0.len){ raiseIndexError2(byte_idx,message_p0.len-1); goto BeforeRet_;
							}
							extracted = ((NI64) ((NU8)((NU8)((NU8)(message_p0.p->data[byte_idx]) >> (NU64)(shift)) & mask_3)));
							value_3 = (NI64)((NI64)((NU64)(value_3) << (NU64)(take)) | extracted);
							if (nimAddInt(bits_collected, take, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_58)) { raiseOverflow(); goto BeforeRet_;
							};
							bits_collected = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_58);
							if (nimAddInt(bit_pos, take, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_59)) { raiseOverflow(); goto BeforeRet_;
							};
							bit_pos = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_59);
						} LA26: ;
					} LA25: ;
					add__winternitz_u1069((&result), value_3);
					if (nimAddInt(res_2, colontmp__4, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_60)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_60);
				} LA24: ;
			}
		}
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, to_bytes__winternitz_u1307)(NI64 value_p0, NI c_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = newSeq__stdZsysrand_u136(((NI)0));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_65;
				if (!(i_2 < c_p1)) goto LA3;
				i = i_2;
				{
					NU8 colontmpD_;
					NI shift;
					NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_64;
					if (!(i < ((NI)8))) goto LA6_;
					colontmpD_ = (NU8)0;
					if (nimMulInt(i, ((NI)8), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_64)) { raiseOverflow(); goto BeforeRet_;
					};
					shift = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_64);
					colontmpD_ = ((NU8) ((NI64)((NI64)((NI64)(((NI64) ((NI)((NI64)(((NI)255)) >> (NU64)(shift)))) & value_p0)) >> (NU64)(shift))));
					add__pureZtimes_u2296((&result), colontmpD_);
				}
				goto LA4_;
LA6_: ;
				{
					add__pureZtimes_u2296((&result), ((NU8)0));
				}
LA4_: ;
				if (nimAddInt(i_2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_65)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_65);
			} LA3: ;
		}
	}
	reverse__winternitz_u1340(((result).p) ? (result.p->data) : NIM_NIL, result.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8*, sign__winternitz_u1368)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, tySequence__aLjCOs9bu5l2rz6ENM6m6Sg secret_key_p1, NI n_p2, NI w_p3) {
	NU8* result;
	tySequence__IHUFRsFxZNv7YydiUO2esQ b;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
	tySequence__IHUFRsFxZNv7YydiUO2esQ colontmpD__2;
	NI a;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_41;
	NI pow_w;
	NI c;
	NF T1_;
	NF T2_;
	NI64 c_sum;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_61;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_62;
	NI64 T3_;
	NI64 TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_63;
	void* z_raw;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_66;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8*)0;
	b.len = 0; b.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	if (w_p3 == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(n_p2, w_p3, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_41)) { raiseOverflow(); goto BeforeRet_;
	};
	a = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_41);
	pow_w = (NI)((NU64)(((NI)1)) << (NU64)(w_p3));
	T1_ = (NF)0;
	T1_ = log2(((NF)(((NF) (a))) * (NF)(((NF)(((NF) (pow_w))) - (NF)(1.0)))));
	T2_ = (NF)0;
	T2_ = ceil(((NF)(T1_) / (NF)(((NF) (w_p3)))));
	c = ((NI) (T2_));
	b = split__winternitz_u1039(message_p0, w_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimSubInt(pow_w, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_61)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt(a, (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_61), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_62)) { raiseOverflow(); goto BeforeRet_;
	};
	T3_ = (NI64)0;
	T3_ = sum__winternitz_u1382(((b).p) ? (b.p->data) : NIM_NIL, b.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimSubInt64(((NI64) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_62))), T3_, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_63)) { raiseOverflow(); goto BeforeRet_;
	};
	c_sum = (NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_63);
	colontmpD_ = to_bytes__winternitz_u1307(c_sum, c);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__2 = split__winternitz_u1039(colontmpD_, w_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__winternitz_u1417((&b), ((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len);
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_66)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_66), (NI)((n_p2) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	z_raw = alloc0Impl__system_u1763(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_67))));
	{
		NI i;
		NI colontmp_;
		NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_68;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_68)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_68);
		i_2 = ((NI)0);
		{
			while (1) {
				NI64 idx;
				NU offset;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_69;
				void* dest;
				NI64 TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_71;
				if (!(i_2 < colontmp_)) goto LA6;
				i = i_2;
				if (i < 0 || i >= b.len){ raiseIndexError2(i,b.len-1); goto BeforeRet_;
				}
				idx = b.p->data[i];
				if (nimMulInt(i, (NI)((n_p2) / (((NI)8))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_69)) { raiseOverflow(); goto BeforeRet_;
				};
				offset = ((NU) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_69)));
				dest = ((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (z_raw))) + (NU64)(offset))));
				if (i < 0 || i >= secret_key_p1.len){ raiseIndexError2(i,secret_key_p1.len-1); goto BeforeRet_;
				}
				if (nimMulInt64(idx, ((NI64) ((NI)((n_p2) / (((NI)8))))), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70) < 0 || (NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70) >= secret_key_p1.p->data[i].len){ raiseIndexError2((NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70),secret_key_p1.p->data[i].len-1); goto BeforeRet_;
				}
				if (((NI)((n_p2) / (((NI)8)))) < ((NI)0) || ((NI)((n_p2) / (((NI)8)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_p2) / (((NI)8))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				copyMem__system_u1745(dest, ((void*) ((&secret_key_p1.p->data[i].p->data[(NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_70)]))), ((NI) ((NI)((n_p2) / (((NI)8))))));
				if (nimAddInt(i_2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_71)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_71);
			} LA6: ;
		}
	}
	result = ((NU8*) (z_raw));
	eqdestroy___winternitz_u1185(colontmpD__2);
	eqdestroy___pureZtimes_u2338(colontmpD_);
	eqdestroy___winternitz_u1185(b);
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NU8*, sign)(NU8* message_p0, NU8* secret_key_p1, NI n_p2, NI w_p3) {
	NU8* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg_seq;
	tySequence__aLjCOs9bu5l2rz6ENM6m6Sg sk_seq;
	NI a;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_33;
	NI pow_w;
	NI c;
	NF T1_;
	NF T2_;
	NI block_size;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34;
	NU8* T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	msg_seq.len = 0; msg_seq.p = NIM_NIL;
	sk_seq.len = 0; sk_seq.p = NIM_NIL;
	if (w_p3 == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(n_p2, w_p3, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_33)) { raiseOverflow(); goto BeforeRet_;
	};
	a = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_33);
	pow_w = (NI)((NU64)(((NI)1)) << (NU64)(w_p3));
	T1_ = (NF)0;
	T1_ = log2(((NF)(((NF) (a))) * (NF)(((NF)(((NF) (pow_w))) - (NF)(1.0)))));
	T2_ = (NF)0;
	T2_ = ceil(((NF)(T1_) / (NF)(((NF) (w_p3)))));
	c = ((NI) (T2_));
	block_size = (NI)((n_p2) / (((NI)8)));
	if ((block_size) < ((NI)0) || (block_size) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(block_size, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	msg_seq = newSeq__stdZsysrand_u136(((NI) (block_size)));
	if (((NI)0) < 0 || ((NI)0) >= msg_seq.len){ raiseIndexError2(((NI)0),msg_seq.len-1); goto BeforeRet_;
	}
	if ((block_size) < ((NI)0) || (block_size) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(block_size, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1745(((void*) ((&msg_seq.p->data[((NI)0)]))), ((void*) (message_p0)), ((NI) (block_size)));
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	sk_seq = newSeq__winternitz_u950(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_34))));
	{
		NI j;
		NI colontmp_;
		NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_35;
		NI i;
		j = (NI)0;
		colontmp_ = (NI)0;
		if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_35)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_35);
		i = ((NI)0);
		{
			while (1) {
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36;
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T6_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_37;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_38;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_40;
				if (!(i < colontmp_)) goto LA5;
				j = i;
				if (j < 0 || j >= sk_seq.len){ raiseIndexError2(j,sk_seq.len-1); goto BeforeRet_;
				}
				if (nimMulInt(pow_w, block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				T6_.len = 0; T6_.p = NIM_NIL;
				T6_ = newSeq__stdZsysrand_u136(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_36))));
				eqsink___pureZtimes_u2347((&sk_seq.p->data[j]), T6_);
				if (j < 0 || j >= sk_seq.len){ raiseIndexError2(j,sk_seq.len-1); goto BeforeRet_;
				}
				if (((NI)0) < 0 || ((NI)0) >= sk_seq.p->data[j].len){ raiseIndexError2(((NI)0),sk_seq.p->data[j].len-1); goto BeforeRet_;
				}
				if (nimMulInt(j, pow_w, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_37)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_37), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_38)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimMulInt(pow_w, block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				copyMem__system_u1745(((void*) ((&sk_seq.p->data[j].p->data[((NI)0)]))), ((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (secret_key_p1))) + (NU64)(((NU) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_38))))))), ((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_39))));
				if (nimAddInt(i, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_40)) { raiseOverflow(); goto BeforeRet_;
				};
				i = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_40);
			} LA5: ;
		}
	}
	T7_ = (NU8*)0;
	T7_ = sign__winternitz_u1368(msg_seq, sk_seq, n_p2, w_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NU8*) (T7_));
	eqdestroy___winternitz_u961(sk_seq);
	eqdestroy___pureZtimes_u2338(msg_seq);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, verify__winternitz_u1537)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ message_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ signature_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ public_key_p2, NI n_p3, NI w_p4) {
	NIM_BOOL result;
	tySequence__IHUFRsFxZNv7YydiUO2esQ b;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
	tySequence__IHUFRsFxZNv7YydiUO2esQ colontmpD__2;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ computed_pk;
	NI a;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_81;
	NI pow_w;
	NI c;
	NF T2_;
	NF T3_;
	NI block_size;
	NI64 c_sum;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_82;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_83;
	NI64 T4_;
	NI64 TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_84;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	b.len = 0; b.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	computed_pk.len = 0; computed_pk.p = NIM_NIL;
	if (w_p4 == 0){ raiseDivByZero(); goto LA1_;
	}
	if (nimDivInt(n_p3, w_p4, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_81)) { raiseOverflow(); goto LA1_;
	};
	a = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_81);
	pow_w = (NI)((NU64)(((NI)1)) << (NU64)(w_p4));
	T2_ = (NF)0;
	T2_ = log2(((NF)(((NF) (a))) * (NF)(((NF)(((NF) (pow_w))) - (NF)(1.0)))));
	T3_ = (NF)0;
	T3_ = ceil(((NF)(T2_) / (NF)(((NF) (w_p4)))));
	c = ((NI) (T3_));
	block_size = (NI)((n_p3) / (((NI)8)));
	b = split__winternitz_u1039(message_p0, w_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (nimSubInt(pow_w, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_82)) { raiseOverflow(); goto LA1_;
	};
	if (nimMulInt(a, (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_82), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_83)) { raiseOverflow(); goto LA1_;
	};
	T4_ = (NI64)0;
	T4_ = sum__winternitz_u1382(((b).p) ? (b.p->data) : NIM_NIL, b.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (nimSubInt64(((NI64) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_83))), T4_, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_84)) { raiseOverflow(); goto LA1_;
	};
	c_sum = (NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_84);
	colontmpD_ = to_bytes__winternitz_u1307(c_sum, c);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = split__winternitz_u1039(colontmpD_, w_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	add__winternitz_u1417((&b), ((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len);
	computed_pk.len = 0; computed_pk.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	{
		NI i;
		NI colontmp_;
		NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_85;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_85)) { raiseOverflow(); goto LA1_;
		};
		colontmp_ = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_85);
		i_2 = ((NI)0);
		{
			while (1) {
				tySequence__6H5Oh5UUvVCLiakt9aTwtUQ value;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_86;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_87;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_88;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_89;
				tyObject_HSlice__NmJTCUV3TaX66XXmZk8J2Q T8_;
				NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_91;
				if (!(i_2 < colontmp_)) goto LA7;
				value.len = 0; value.p = NIM_NIL;
				i = i_2;
				if (nimMulInt(i, block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_86)) { raiseOverflow(); goto LA1_;
				};
				if (nimAddInt(i, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_87)) { raiseOverflow(); goto LA1_;
				};
				if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_87), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_88)) { raiseOverflow(); goto LA1_;
				};
				if (nimSubInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_88), ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_89)) { raiseOverflow(); goto LA1_;
				};
				T8_ = dotdot___stdZstrbasics_u48((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_86), (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_89));
				value = X5BX5D___winternitz_u100(((signature_p1).p) ? (signature_p1.p->data) : NIM_NIL, signature_p1.len, T8_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					NI64 _;
					NI64 colontmp__2;
					NI64 colontmp__3;
					NI64 res;
					_ = (NI64)0;
					colontmp__2 = (NI64)0;
					colontmp__3 = (NI64)0;
					if (i < 0 || i >= b.len){ raiseIndexError2(i,b.len-1); goto LA1_;
					}
					colontmp__2 = b.p->data[i];
					colontmp__3 = ((NI64) (pow_w));
					res = colontmp__2;
					{
						while (1) {
							tySequence__6H5Oh5UUvVCLiakt9aTwtUQ hashed;
							NI64 TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_90;
							if (!(res < colontmp__3)) goto LA11;
							hashed.len = 0; hashed.p = NIM_NIL;
							_ = res;
							hashed.len = 0; hashed.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
							hash_bytes__winternitz_u74((&value), (&hashed), block_size);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
							eqsink___pureZtimes_u2347((&value), hashed);
							if (nimAddInt64(res, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_90)) { raiseOverflow(); goto LA1_;
							};
							res = (NI64)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_90);
						} LA11: ;
					}
				}
				add__winternitz_u802((&computed_pk), ((value).p) ? (value.p->data) : NIM_NIL, value.len);
				if (nimAddInt(i_2, ((NI)1), &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_91)) { raiseOverflow(); goto LA1_;
				};
				i_2 = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_91);
				eqdestroy___pureZtimes_u2338(value);
			} LA7: ;
		}
	}
	result = eqeq___winternitz_u1603(computed_pk, public_key_p2);
	eqdestroy___pureZtimes_u2338(computed_pk);
	eqdestroy___winternitz_u1185(colontmpD__2);
	eqdestroy___pureZtimes_u2338(colontmpD_);
	eqdestroy___winternitz_u1185(b);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2338(computed_pk);
		eqdestroy___winternitz_u1185(colontmpD__2);
		eqdestroy___pureZtimes_u2338(colontmpD_);
		eqdestroy___winternitz_u1185(b);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NIM_BOOL, verify)(NU8* message_p0, NU8* signature_p1, NU8* public_key_p2, NI n_p3, NI w_p4) {
	NIM_BOOL result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg_seq;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ sig_seq;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ pk_seq;
	NI a;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_72;
	NI pow_w;
	NI c;
	NF T1_;
	NF T2_;
	NI block_size;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_73;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_75;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_77;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_79;
	NI TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	msg_seq.len = 0; msg_seq.p = NIM_NIL;
	sig_seq.len = 0; sig_seq.p = NIM_NIL;
	pk_seq.len = 0; pk_seq.p = NIM_NIL;
	if (w_p4 == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimDivInt(n_p3, w_p4, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_72)) { raiseOverflow(); goto BeforeRet_;
	};
	a = (NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_72);
	pow_w = (NI)((NU64)(((NI)1)) << (NU64)(w_p4));
	T1_ = (NF)0;
	T1_ = log2(((NF)(((NF) (a))) * (NF)(((NF)(((NF) (pow_w))) - (NF)(1.0)))));
	T2_ = (NF)0;
	T2_ = ceil(((NF)(T1_) / (NF)(((NF) (w_p4)))));
	c = ((NI) (T2_));
	block_size = (NI)((n_p3) / (((NI)8)));
	if ((block_size) < ((NI)0) || (block_size) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(block_size, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	msg_seq = newSeq__stdZsysrand_u136(((NI) (block_size)));
	if (((NI)0) < 0 || ((NI)0) >= msg_seq.len){ raiseIndexError2(((NI)0),msg_seq.len-1); goto BeforeRet_;
	}
	if ((block_size) < ((NI)0) || (block_size) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(block_size, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1745(((void*) ((&msg_seq.p->data[((NI)0)]))), ((void*) (message_p0)), ((NI) (block_size)));
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_73)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_73), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	sig_seq = newSeq__stdZsysrand_u136(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_74))));
	if (((NI)0) < 0 || ((NI)0) >= sig_seq.len){ raiseIndexError2(((NI)0),sig_seq.len-1); goto BeforeRet_;
	}
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_75)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_75), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1745(((void*) ((&sig_seq.p->data[((NI)0)]))), ((void*) (signature_p1)), ((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_76))));
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_77)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_77), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	pk_seq = newSeq__stdZsysrand_u136(((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_78))));
	if (((NI)0) < 0 || ((NI)0) >= pk_seq.len){ raiseIndexError2(((NI)0),pk_seq.len-1); goto BeforeRet_;
	}
	if (nimAddInt(a, c, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_79)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_79), block_size, &TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80)) < ((NI)0) || ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1745(((void*) ((&pk_seq.p->data[((NI)0)]))), ((void*) (public_key_p2)), ((NI) ((NI)(TM__Kyb9b9cqAh9bDzSCeiKZAPvUQ_80))));
	result = verify__winternitz_u1537(msg_seq, sig_seq, pk_seq, n_p3, w_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZtimes_u2338(pk_seq);
	eqdestroy___pureZtimes_u2338(sig_seq);
	eqdestroy___pureZtimes_u2338(msg_seq);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatspureatsrandomdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatscpufeaturesdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatssha2atssha2_avxdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnimcryptominus0dot7dot3minusf72b90fe3f4da09efa482de4f8729e7ee4abea2fatsnimcryptoatssha2atssha2dotnim_Init000();
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsDownloadsatsnimminus2dot0dot8_x64atsnimminus2dot0dot8atslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	nimTestErrorFlag();
}
}

